# Generated by Django 3.0.7 on 2020-06-24 02:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kefnum', '0002_auto_20200601_2116'),
    ]

    operations = [
        migrations.AddField(
            model_name='desk',
            name='cor',
            field=models.CharField(default='kefnum', max_length=10),
        ),
    ]
