# Generated by Django 3.0.7 on 2020-07-17 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kefnum', '0003_desk_cor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='desk',
            name='cor',
            field=models.CharField(default='kefnum', max_length=50),
        ),
    ]
